language: php
php:
- 7
install:
- composer self-update
- composer install --dev --no-interaction
script:
- vendor/bin/phpunit --testsuite unit --coverage-clover build/logs/clover.xml
- bash bin/codeclimate.sh
