language: php
php:
- 7.1
install:
- composer self-update
- composer install --dev --no-interaction
script:
- vendor/bin/phpunit --testsuite unit --coverage-clover build/logs/clover.xml
- bash bin/codeclimate.sh
after_success:
- bash bin/deploy.sh
